name: picon
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:

  # ------------------------------------------------------------------------------------------------
  # CORE
  # ------------------------------------------------------------------------------------------------

  flutter:
    sdk: flutter

  # DESIGN (WITHOUT NATIVE)
  flutter_svg: ^2.2.0

  # DESIGN (WITH NATIVE)
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  flutter_cache_manager: ^3.4.1

  # LOGICS (WITHOUT NATIVE)
  http: ^1.4.0
  intl: ^0.20.2

  # LOGICS (WITH NATIVE)
  awesome_notifications: ^0.10.1
  awesome_notifications_core: ^0.10.1
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.5.0
  hive_flutter: ^1.1.0
  in_app_review: ^2.0.10
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.1
  share_plus: ^11.0.0
  url_launcher: ^6.3.2

  # ------------------------------------------------------------------------------------------------
  # IF NEEDED
  # ------------------------------------------------------------------------------------------------

  # DESIGN (WITHOUT NATIVE)
  animated_text_kit: ^4.2.3
  carousel_slider: ^5.1.1
  lottie: ^3.3.1
  modal_bottom_sheet: ^3.0.0
  table_calendar: ^3.2.0

  # DESIGN (WITH NATIVE)
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  wakelock_plus: ^1.3.2

  # LOGICS (WITHOUT NATIVE)
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3

  # LOGICS (WITH NATIVE)
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.2.4
  flutter_tts: ^4.2.3
  path: ^1.9.1
  path_provider: ^2.1.5
  translator: ^1.0.3+1
  video_player: ^2.10.0
  web: ^1.1.1

  # AUTHORIZATION (WITH NATIVE)
  local_auth: ^2.3.0       # BIOMETRIC SIGN IN
  google_sign_in: ^6.3.0    # GOOGLE SIGN IN
  sign_in_with_apple: ^7.0.1  # APPLE SIGN IN

  # FIREBASE (WITH NATIVE)
  cloud_firestore: ^5.6.11
  firebase_analytics: ^11.5.2
  firebase_app_check: ^0.3.2+9
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_crashlytics: ^4.3.9
  firebase_database: ^11.3.9
  firebase_remote_config: ^5.4.7
  firebase_storage: ^12.4.9

  # ------------------------------------------------------------------------------------------------
  # DEVELOPER CHOICE
  # ------------------------------------------------------------------------------------------------

  # DESIGN
  flutter_androssy_dialogs: ^1.0.13+1
  flutter_androssy_kits: ^1.0.13

  # LOGICS (WITHOUT PLATFORM)
  app_color: ^1.1.0
  app_dimen: ^1.0.11
  auth_management: ^3.0.2
  data_management: ^2.1.9
  data_management_local_delegate: ^1.0.7
  flutter_andomie: ^0.6.40
  flutter_app_navigator: ^1.0.1
  flutter_device_config: ^1.0.3
  flutter_entity: ^1.2.0
  #  flutter_local_storage: ^0.0.1
  flutter_network_status: ^1.0.0
  in_app_database: ^1.3.3
  in_app_navigator: ^1.0.6
  in_app_purchaser: ^1.0.1

  # ------------------------------------------------------------------------------------------------
  # OTHER
  # ------------------------------------------------------------------------------------------------

dev_dependencies:

  # ------------------------------------------------------------------------------------------------
  # CORE
  # ------------------------------------------------------------------------------------------------

  flutter_test:
    sdk: flutter

  mockito: ^5.4.5
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1

  # ------------------------------------------------------------------------------------------------
  # OTHER
  # ------------------------------------------------------------------------------------------------

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/app/logo_light.png
  image_dark: assets/app/logo_dark.png

  android_12:
    image: assets/app/logo_light.png
    image_dark: assets/app/logo_dark.png
    color: "#ffffff"
    color_dark: "#000000"
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#000000"


  color_web: "#ffffff"
  color_dark_web: "#000000"

  android: true
  ios: true
  web: true

  fullscreen: true

  # Please note that the splash screen will be clipped to a circle on the center of the screen.
  # App icon with an icon background: This should be 960Ã—960 pixels, and fit within a circle
  # 640 pixels in diameter.

flutter:

  # ------------------------------------------------------------------------------------------------
  # DESIGN
  # ------------------------------------------------------------------------------------------------

  uses-material-design: true

  # ------------------------------------------------------------------------------------------------
  # ASSETS
  # ------------------------------------------------------------------------------------------------

  assets:
    - assets/
    - assets/app/
    - assets/configs/
    - assets/contents/
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/videos/


  # ------------------------------------------------------------------------------------------------
  # FONTS
  # ------------------------------------------------------------------------------------------------

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter/thin.ttf
          weight: 100
        - asset: assets/fonts/inter/extra_light.ttf
          weight: 200
        - asset: assets/fonts/inter/light.ttf
          weight: 300
        - asset: assets/fonts/inter/regular.ttf
          weight: 400
        - asset: assets/fonts/inter/medium.ttf
          weight: 500
        - asset: assets/fonts/inter/semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter/bold.ttf
          weight: 700
        - asset: assets/fonts/inter/extra_bold.ttf
          weight: 800
        - asset: assets/fonts/inter/black.ttf
          weight: 900

  # ------------------------------------------------------------------------------------------------
  # OTHER
  # ------------------------------------------------------------------------------------------------
